# Generated by Django 5.2.12 on 2026-04-05 21:13

from collections import defaultdict

from django.conf import settings
from django.db import migrations, models


def dedupe_employees_per_company_user(apps, schema_editor):
    """Un solo Employee por (company, user) antes de aplicar UniqueConstraint."""
    Employee = apps.get_model("staff", "Employee")
    EmployeeTeam = apps.get_model("staff", "EmployeeTeam")
    EmployeeProject = apps.get_model("staff", "EmployeeProject")
    CommissionEvent = apps.get_model("commissions", "CommissionEvent")
    CommissionLine = apps.get_model("commissions", "CommissionLine")
    CommissionPlanEmployee = apps.get_model("rules", "CommissionPlanEmployee")

    qs = Employee.objects.filter(user__isnull=False).order_by("company_id", "user_id", "pk")
    groups = defaultdict(list)
    for row in qs:
        groups[(row.company_id, row.user_id)].append(row)

    for (_company_id, _user_id), rows in groups.items():
        if len(rows) <= 1:
            continue
        keeper_id = rows[0].pk
        for dup in rows[1:]:
            dup_id = dup.pk
            CommissionEvent.objects.filter(employee_id=dup_id).update(employee_id=keeper_id)
            CommissionLine.objects.filter(employee_id=dup_id).update(employee_id=keeper_id)
            for cpe in list(CommissionPlanEmployee.objects.filter(employee_id=dup_id)):
                if CommissionPlanEmployee.objects.filter(plan_id=cpe.plan_id, employee_id=keeper_id).exists():
                    cpe.delete()
                else:
                    cpe.employee_id = keeper_id
                    cpe.save(update_fields=["employee_id"])
            for et in list(EmployeeTeam.objects.filter(employee_id=dup_id)):
                if EmployeeTeam.objects.filter(employee_id=keeper_id, team_id=et.team_id).exists():
                    et.delete()
                else:
                    et.employee_id = keeper_id
                    et.save(update_fields=["employee_id"])
            for ep in list(EmployeeProject.objects.filter(employee_id=dup_id)):
                if EmployeeProject.objects.filter(employee_id=keeper_id, project_id=ep.project_id).exists():
                    ep.delete()
                else:
                    ep.employee_id = keeper_id
                    ep.save(update_fields=["employee_id"])
            Employee.objects.filter(pk=dup_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("projects", "0001_initial"),
        ("rules", "0003_commissionrule_plan_required"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_employees_per_company_user, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("company", "user"),
                name="staff_employee_unique_user_per_company",
            ),
        ),
    ]
