# Generated by Django 5.2.12 on 2026-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteamscope',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Permisos elevados solo dentro de este equipo (p. ej. aprobar, gestionar miembros del equipo).'),
        ),
    ]
