# Generated by Django 5.2.12 on 2026-04-03 07:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('closed', 'Cerrado')], default='draft', max_length=16)),
                ('fx_policy', models.CharField(choices=[('operation_date', 'Fecha de operación'), ('period_end', 'Fin de periodo')], default='operation_date', max_length=32)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommissionLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('pending_approval', 'Pendiente aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('adjusted', 'Ajustado'), ('paid', 'Pagado')], default='pending', max_length=32)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_explanation', models.TextField(blank=True)),
                ('fx_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical commission line',
                'verbose_name_plural': 'historical commission lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectCommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=32)),
                ('log', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_kind', models.CharField(max_length=120)),
                ('occurred_on', models.DateField()),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_business_hours', models.BooleanField(blank=True, null=True)),
                ('sales_channel', models.CharField(blank=True, max_length=120)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_events', to='staff.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_events', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_events', to='projects.team')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('correction', 'Corrección'), ('refund', 'Reembolso'), ('suspension', 'Suspensión'), ('extra_discount', 'Descuento extraordinario'), ('other', 'Otro')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_adjustments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='commissions.commissionevent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('pending_approval', 'Pendiente aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('adjusted', 'Ajustado'), ('paid', 'Pagado')], default='pending', max_length=32)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_explanation', models.TextField(blank=True)),
                ('fx_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_lines', to='staff.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commissions.commissionevent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
