# Generated by Django 5.2.12 on 2026-04-03 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('rules', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionline',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='rules.commissionrule'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='commissions.commissionline'),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='commissionevent',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commissions.commissionperiod'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='commissions.commissionperiod'),
        ),
        migrations.AddField(
            model_name='commissiontype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='commissionline',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='commissions.commissiontype'),
        ),
        migrations.AddField(
            model_name='commissionevent',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.commissiontype'),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='commission_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commissions.commissiontype'),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commissions.commissionevent'),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcommissionline',
            name='rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.commissionrule'),
        ),
        migrations.AddField(
            model_name='projectcommissiontype',
            name='commission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='commissions.commissiontype'),
        ),
        migrations.AddField(
            model_name='projectcommissiontype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_commission_types', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='commissionperiod',
            index=models.Index(fields=['company', 'state'], name='commissions_company_fa6028_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commissiontype',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='commissionline',
            index=models.Index(fields=['company', 'employee', 'state'], name='commissions_company_6988f4_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionevent',
            index=models.Index(fields=['company', 'period', 'project'], name='commissions_company_b8e8b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcommissiontype',
            unique_together={('project', 'commission_type')},
        ),
    ]
