# Generated by Django 5.2.12 on 2026-04-04 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commissionevent_fx_rate'),
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionevent',
            name='fx_rate',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si se elige, el monto está en fx_rate.currency_code; value del tipo de cambio = unidades de moneda base de la compañía por 1 unidad de esa moneda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events', to='fx.fxrate'),
        ),
    ]
