# Generated by Django 5.2.12 on 2026-04-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Emoji o texto corto mostrado junto al título en el índice.', max_length=32)),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='manuals.manualpage')),
            ],
            options={
                'verbose_name': 'Página del manual',
                'verbose_name_plural': 'Páginas del manual',
                'ordering': ['parent_id', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['parent', 'sort_order'], name='manuals_man_parent__b7cce2_idx')],
            },
        ),
    ]
