# Generated by Django 5.2.12 on 2026-04-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('rate_date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['-rate_date', 'currency_code'],
                'indexes': [models.Index(fields=['company', 'currency_code', 'rate_date'], name='fx_fxrate_company_a9d9a0_idx')],
                'unique_together': {('company', 'currency_code', 'rate_date')},
            },
        ),
    ]
