# Generated by Django 5.2.12 on 2026-04-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_initial"),
        ("companies", "0001_initial"),
        ("projects", "0001_initial"),
        ("rules", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="RuleSet", new_name="CommissionPlan"),
        migrations.AddField(
            model_name="commissionplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el plan aplica a todos los eventos (filtrado por proyecto del plan si existe).",
            ),
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commissionplan",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_plans",
                to="projects.project",
            ),
        ),
        migrations.RenameField(
            model_name="commissionrule",
            old_name="rule_set",
            new_name="plan",
        ),
        migrations.RenameField(
            model_name="historicalcommissionrule",
            old_name="rule_set",
            new_name="plan",
        ),
        migrations.CreateModel(
            name="CommissionPlanTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_teams",
                        to="rules.commissionplan",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_plan_teams",
                        to="projects.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionPlanEmployee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_plan_employees",
                        to="staff.employee",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_employees",
                        to="rules.commissionplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="commission_plans",
                through="rules.CommissionPlanEmployee",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="commissionplan",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="commission_plans",
                through="rules.CommissionPlanTeam",
                to="projects.team",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrule",
            index=models.Index(fields=["company", "plan"], name="rules_commi_company_72033f_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionplanemployee",
            index=models.Index(fields=["plan", "employee"], name="rules_commi_plan_id_989eb3_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionplanemployee",
            index=models.Index(
                fields=["employee", "valid_from", "valid_to"],
                name="rules_commi_employe_d34d0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionplanteam",
            index=models.Index(fields=["plan", "team"], name="rules_commi_plan_id_587db9_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionplanteam",
            index=models.Index(
                fields=["team", "valid_from", "valid_to"],
                name="rules_commi_team_id_f3b502_idx",
            ),
        ),
    ]
